import { format } from "date-fns";
import type { Category, Event, Organization, TicketType } from "@/store/api/event/event.type";

const now = new Date();
const inOneWeek = new Date(now.getTime() + 7 * 24 * 60 * 60 * 1000);
const inTwoWeeks = new Date(now.getTime() + 14 * 24 * 60 * 60 * 1000);
const inThreeWeeks = new Date(now.getTime() + 21 * 24 * 60 * 60 * 1000);
const lastWeek = new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000);

const formatDate = (d: Date) => d.toISOString();

export const mockCategories: Category[] = [
  { id: "cat-1", name: "Concert", slug: "concert" },
  { id: "cat-2", name: "Festival", slug: "festival" },
  { id: "cat-3", name: "Sport", slug: "sport" },
  { id: "cat-4", name: "Conférence", slug: "conference" },
  { id: "cat-5", name: "Théâtre", slug: "theatre" },
  { id: "cat-6", name: "Gastronomie", slug: "gastronomie" },
  { id: "cat-7", name: "Art", slug: "art" },
];

const mockOrg: Organization = {
  id: "org-1",
  name: "Tukki Events",
  slug: "tukki-events",
  description: "Organisateur d'événements à Dakar",
  logoUrl: "/images/hero.jpg",
  websiteUrl: "https://tukkiapp.com",
};

function makeTicketType(
  eventId: string,
  name: string,
  price: number,
  overrides: Partial<TicketType> = {}
): TicketType {
  return {
    id: `tt-${eventId}-${name}`,
    eventId,
    name,
    price,
    minPurchase: 1,
    maxPurchase: 10,
    isVisible: true,
    requiresApproval: false,
    sortOrder: 0,
    event: {} as Event,
    tickets: [],
    createdAt: formatDate(now),
    updatedAt: formatDate(now),
    ...overrides,
  };
}

export const mockEvents: Event[] = [
  {
    id: "ev-1",
    slug: "festival-mbalakh",
    title: "Festival Mbalakh - Édition 2025",
    description: "Grand festival de musique et culture à Dakar.",
    startDatetime: formatDate(inOneWeek),
    endDatetime: formatDate(inOneWeek),
    status: "PUBLISHED",
    thumbnailUrl: "https://picsum.photos/seed/mbalakh/400/300",
    coverImageUrl: "https://picsum.photos/seed/mbalakh/800/500",
    isFeatured: true,
    isOnline: false,
    isPublished: true,
    latitude: "14.7167",
    longitude: "-17.4677",
    city: "Dakar",
    address: "Place de l'Obélisque, Dakar",
    capacity: 5000,
    categoryId: "cat-2",
    organizationId: mockOrg.id,
    shortDescription: "Festival de musique et culture",
    metaDescription: "Festival Mbalakh Dakar 2025",
    metaTitle: "Festival Mbalakh",
    minAge: 0,
    onlineLink: "",
    createdAt: formatDate(lastWeek),
    updatedAt: formatDate(now),
    organization: mockOrg,
    category: mockCategories[1],
    ticketTypes: [
      makeTicketType("ev-1", "Standard", 15000),
      makeTicketType("ev-1", "VIP", 35000),
    ],
    tickets: [],
  },
  {
    id: "ev-2",
    slug: "concert-ndongo-darou",
    title: "Concert Ndongo Darou & Band",
    description: "Soirée live avec Ndongo Darou au Thiossane.",
    startDatetime: formatDate(inTwoWeeks),
    endDatetime: formatDate(inTwoWeeks),
    status: "PUBLISHED",
    thumbnailUrl: "https://picsum.photos/seed/ndongo/400/300",
    coverImageUrl: "https://picsum.photos/seed/ndongo/800/500",
    isFeatured: true,
    isOnline: false,
    isPublished: true,
    latitude: "14.7167",
    longitude: "-17.4677",
    city: "Dakar",
    address: "Thiossane, Dakar",
    capacity: 800,
    categoryId: "cat-1",
    organizationId: mockOrg.id,
    shortDescription: "Concert live",
    metaDescription: "Concert Ndongo Darou Dakar",
    metaTitle: "Concert Ndongo Darou",
    minAge: 0,
    onlineLink: "",
    createdAt: formatDate(lastWeek),
    updatedAt: formatDate(now),
    organization: mockOrg,
    category: mockCategories[0],
    ticketTypes: [
      makeTicketType("ev-2", "Entrée", 5000),
      makeTicketType("ev-2", "Table 4 pers.", 25000),
    ],
    tickets: [],
  },
  {
    id: "ev-3",
    slug: "match-basket-dakar",
    title: "Match de basket : Dakar vs Thiès",
    description: "Rencontre de basket-ball entre les équipes de Dakar et Thiès.",
    startDatetime: formatDate(inOneWeek),
    endDatetime: formatDate(inOneWeek),
    status: "PUBLISHED",
    thumbnailUrl: "https://picsum.photos/seed/basket/400/300",
    coverImageUrl: "https://picsum.photos/seed/basket/800/500",
    isFeatured: false,
    isOnline: false,
    isPublished: true,
    latitude: "14.7167",
    longitude: "-17.4677",
    city: "Dakar",
    address: "Stade Iba Mar Diop, Dakar",
    capacity: 3000,
    categoryId: "cat-3",
    organizationId: mockOrg.id,
    shortDescription: "Match de basket",
    metaDescription: "Basket Dakar Thiès",
    metaTitle: "Match basket Dakar Thiès",
    minAge: 0,
    onlineLink: "",
    createdAt: formatDate(now),
    updatedAt: formatDate(now),
    organization: mockOrg,
    category: mockCategories[2],
    ticketTypes: [makeTicketType("ev-3", "Tribune", 2000)],
    tickets: [],
  },
  {
    id: "ev-4",
    slug: "tech-summit-dakar",
    title: "Tech Summit Dakar 2025",
    description: "Conférences et ateliers tech pour entrepreneurs et développeurs.",
    startDatetime: formatDate(inThreeWeeks),
    endDatetime: formatDate(inThreeWeeks),
    status: "PUBLISHED",
    thumbnailUrl: "https://picsum.photos/seed/tech/400/300",
    coverImageUrl: "https://picsum.photos/seed/tech/800/500",
    isFeatured: true,
    isOnline: true,
    isPublished: true,
    latitude: "",
    longitude: "",
    city: "Dakar",
    address: "En ligne",
    capacity: 500,
    categoryId: "cat-4",
    organizationId: mockOrg.id,
    shortDescription: "Conférence tech",
    metaDescription: "Tech Summit Dakar",
    metaTitle: "Tech Summit Dakar 2025",
    minAge: 0,
    onlineLink: "https://example.com/tech-summit",
    createdAt: formatDate(now),
    updatedAt: formatDate(now),
    organization: mockOrg,
    category: mockCategories[3],
    ticketTypes: [
      makeTicketType("ev-4", "Gratuit", 0),
      makeTicketType("ev-4", "Premium", 10000),
    ],
    tickets: [],
  },
  {
    id: "ev-5",
    slug: "piece-theatre-souffles",
    title: "Souffles - Pièce de théâtre",
    description: "Une création contemporaine de la troupe Théâtre du Soleil.",
    startDatetime: formatDate(inTwoWeeks),
    endDatetime: formatDate(inTwoWeeks),
    status: "PUBLISHED",
    thumbnailUrl: "https://picsum.photos/seed/theatre/400/300",
    coverImageUrl: "https://picsum.photos/seed/theatre/800/500",
    isFeatured: false,
    isOnline: false,
    isPublished: true,
    latitude: "14.7167",
    longitude: "-17.4677",
    city: "Dakar",
    address: "Salle Sorano, Dakar",
    capacity: 400,
    categoryId: "cat-5",
    organizationId: mockOrg.id,
    shortDescription: "Théâtre contemporain",
    metaDescription: "Souffles théâtre Dakar",
    metaTitle: "Souffles - Théâtre",
    minAge: 12,
    onlineLink: "",
    createdAt: formatDate(lastWeek),
    updatedAt: formatDate(now),
    organization: mockOrg,
    category: mockCategories[4],
    ticketTypes: [
      makeTicketType("ev-5", "Plein tarif", 8000),
      makeTicketType("ev-5", "Réduit", 4000),
    ],
    tickets: [],
  },
  {
    id: "ev-6",
    slug: "degustation-terroir",
    title: "Dégustation Terroir Sénégal",
    description: "Découverte des saveurs et produits du terroir sénégalais.",
    startDatetime: formatDate(inOneWeek),
    endDatetime: formatDate(inOneWeek),
    status: "PUBLISHED",
    thumbnailUrl: "https://picsum.photos/seed/terroir/400/300",
    coverImageUrl: "https://picsum.photos/seed/terroir/800/500",
    isFeatured: false,
    isOnline: false,
    isPublished: true,
    latitude: "14.7167",
    longitude: "-17.4677",
    city: "Dakar",
    address: "Marché Kermel, Dakar",
    capacity: 60,
    categoryId: "cat-6",
    organizationId: mockOrg.id,
    shortDescription: "Dégustation gastronomique",
    metaDescription: "Dégustation terroir Dakar",
    metaTitle: "Dégustation Terroir",
    minAge: 0,
    onlineLink: "",
    createdAt: formatDate(now),
    updatedAt: formatDate(now),
    organization: mockOrg,
    category: mockCategories[5],
    ticketTypes: [makeTicketType("ev-6", "Place", 12000)],
    tickets: [],
  },
  {
    id: "ev-7",
    slug: "expo-art-contemporain",
    title: "Expo Art Contemporain - Raw Material",
    description: "Exposition d'art contemporain africain à Raw Material Company.",
    startDatetime: formatDate(inTwoWeeks),
    endDatetime: formatDate(inThreeWeeks),
    status: "PUBLISHED",
    thumbnailUrl: "https://picsum.photos/seed/art/400/300",
    coverImageUrl: "https://picsum.photos/seed/art/800/500",
    isFeatured: false,
    isOnline: false,
    isPublished: true,
    latitude: "14.7167",
    longitude: "-17.4677",
    city: "Dakar",
    address: "Raw Material Company, Dakar",
    capacity: 200,
    categoryId: "cat-7",
    organizationId: mockOrg.id,
    shortDescription: "Exposition d'art",
    metaDescription: "Art contemporain Dakar",
    metaTitle: "Expo Art Contemporain",
    minAge: 0,
    onlineLink: "",
    createdAt: formatDate(now),
    updatedAt: formatDate(now),
    organization: mockOrg,
    category: mockCategories[6],
    ticketTypes: [makeTicketType("ev-7", "Entrée", 0)],
    tickets: [],
  },
  {
    id: "ev-8",
    slug: "soiree-jazz-sunugal",
    title: "Soirée Jazz au Sunugal",
    description: "Soirée jazz avec orchestre live et restauration.",
    startDatetime: formatDate(inThreeWeeks),
    endDatetime: formatDate(inThreeWeeks),
    status: "PUBLISHED",
    thumbnailUrl: "https://picsum.photos/seed/jazz/400/300",
    coverImageUrl: "https://picsum.photos/seed/jazz/800/500",
    isFeatured: true,
    isOnline: false,
    isPublished: true,
    latitude: "14.7167",
    longitude: "-17.4677",
    city: "Dakar",
    address: "Sunugal, Almadies, Dakar",
    capacity: 150,
    categoryId: "cat-1",
    organizationId: mockOrg.id,
    shortDescription: "Soirée jazz",
    metaDescription: "Jazz Sunugal Dakar",
    metaTitle: "Soirée Jazz Sunugal",
    minAge: 0,
    onlineLink: "",
    createdAt: formatDate(lastWeek),
    updatedAt: formatDate(now),
    organization: mockOrg,
    category: mockCategories[0],
    ticketTypes: [
      makeTicketType("ev-8", "Consommation incluse", 7500),
      makeTicketType("ev-8", "Dîner + concert", 18000),
    ],
    tickets: [],
  },
];

// Booked tickets (for My Tickets / Ticket detail) - can be extended by OrdersContext
export interface BookedTicket {
  id: string;
  orderId: string;
  status: "valid" | "used";
  eventId: string;
  eventSlug: string;
  eventImage: string;
  eventTitle: string;
  eventDate: string;
  eventTime: string;
  /** ISO date string for sorting/filtering */
  eventDatetime?: string;
  eventLocation: string;
  ticketType: string;
  quantity: number;
  totalPrice: number;
  ticketNumber: string;
  qrCode: string;
  holderName: string;
  buyerEmail?: string;
  buyerPhone?: string;
  purchaseDate: string;
}

// Initial mock booked tickets for demo (optional)
export const mockBookedTickets: BookedTicket[] = [
  {
    id: "bt-1",
    orderId: "ORD-MOCK-1",
    status: "valid",
    eventId: mockEvents[0].id,
    eventSlug: mockEvents[0].slug,
    eventImage: mockEvents[0].coverImageUrl,
    eventTitle: mockEvents[0].title,
    eventDate: format(new Date(mockEvents[0].startDatetime), "dd MMM yyyy"),
    eventTime: format(new Date(mockEvents[0].startDatetime), "HH:mm"),
    eventDatetime: mockEvents[0].startDatetime,
    eventLocation: mockEvents[0].city + (mockEvents[0].address ? `, ${mockEvents[0].address}` : ""),
    ticketType: "Standard",
    quantity: 2,
    totalPrice: 30000,
    ticketNumber: "TKK-2025-001",
    qrCode: "TKK-EV1-TKK-2025-001",
    holderName: "Amadou Diallo",
    buyerEmail: "amadou@example.com",
    buyerPhone: "+221771234567",
    purchaseDate: format(now, "dd MMM yyyy"),
  },
];
